import {
  type ContestantClass,
  type ContestantSpecialization,
  type ContestantWeapon,
} from '../schema';

export const heavyClass: ContestantClass = {
  description:
    'Durable powerhouse specializing in area control and high damage output.',
  healthPoints: 350,
  id: 'heavy-contestant',
  imageUrl: '/images/contestants/heavy.png',
  label: 'Heavy',
  regenerationSeconds: 10,
  type: 'heavy',
};

export const heavyWeapons: ContestantWeapon[] = [
  {
    classType: 'heavy',
    damageBodyMax: 44,
    damageBodyMin: 44,
    damageCriticalMultiplier: 2,
    damageCriticalType: 'headshot',
    description: 'Dual pistols that can also be used as snipers.',
    id: '50-akimbo',
    imageUrl: '/images/weapons/50-akimbo.png',
    label: '.50 Akimbo',
    type: 'handgun',
  },
  {
    classType: 'heavy',
    damageBodyMax: 30,
    damageBodyMin: 30,
    damageCriticalMultiplier: 1,
    damageCriticalType: 'none',
    description:
      'A flamethrower that is always more effective when used by your enemies.',
    id: 'flamethrower',
    imageUrl: '/images/weapons/flamethrower.png',
    label: 'Flamethrower',
    type: 'assault-rifle',
  },
  {
    classType: 'heavy',
    damageBodyMax: 100,
    damageBodyMin: 100,
    damageCriticalMultiplier: 1,
    damageCriticalType: 'none',
    description:
      'A shotgun with slugs that can destroy walls and floors in four shots.',
    id: 'ks-23',
    imageUrl: '/images/weapons/ks-23.png',
    label: 'KS-23',
    type: 'shotgun',
  },
  {
    classType: 'heavy',
    damageBodyMax: 22,
    damageBodyMin: 22,
    damageCriticalMultiplier: 1.5,
    damageCriticalType: 'headshot',
    description:
      'Similar to the M60 but with more accuracy and a smaller clip size.',
    id: 'lewis-gun',
    imageUrl: '/images/weapons/lewis-gun.png',
    label: 'Lewis Gun',
    type: 'lmg',
  },
  {
    classType: 'heavy',
    damageBodyMax: 83,
    damageBodyMin: 83,
    damageCriticalMultiplier: 1,
    damageCriticalType: 'none',
    description: 'A grenade launcher with bouncy grenades.',
    id: 'm32gl',
    imageUrl: '/images/weapons/m32gl.png',
    label: 'M32GL',
    type: 'grenade-launcher',
  },
  {
    classType: 'heavy',
    damageBodyMax: 19,
    damageBodyMin: 19,
    damageCriticalMultiplier: 1.5,
    damageCriticalType: 'headshot',
    description:
      'Less accurate than the Lewis Gun but with a larger clip size.',
    id: 'm60',
    imageUrl: '/images/weapons/m60.png',
    label: 'M60',
    type: 'lmg',
  },
  {
    classType: 'heavy',
    damageBodyMax: 78,
    damageBodyMin: 13,
    damageCriticalMultiplier: 1,
    damageCriticalType: 'none',
    description:
      'A mysterious gun that is typically ineffective but can excel in the right hands.',
    id: 'sa1216',
    imageUrl: '/images/weapons/sa1216.png',
    label: 'SA1216',
    type: 'shotgun',
  },
  {
    classType: 'heavy',
    damageBodyMax: 30,
    damageBodyMin: 30,
    damageCriticalMultiplier: 1.5,
    damageCriticalType: 'headshot',
    description: 'A highly enjoyable weapon with excellent performance.',
    id: 'shak-50',
    imageUrl: '/images/weapons/shak-50.png',
    label: 'ShAk-50',
    type: 'shotgun',
  },
  {
    classType: 'heavy',
    damageBodyMax: 115,
    damageBodyMin: 115,
    damageCriticalMultiplier: 1.74,
    damageCriticalType: 'alt',
    description: 'A massive hammer designed for delivering powerful strikes.',
    id: 'sledgehammer',
    imageUrl: '/images/weapons/sledgehammer.png',
    label: 'Sledgehammer',
    type: 'melee',
  },
  {
    classType: 'heavy',
    damageBodyMax: 90,
    damageBodyMin: 65,
    damageCriticalMultiplier: 1.62,
    damageCriticalType: 'alt',
    description: 'A large spear capable of wide swings and spinning attacks.',
    id: 'spear',
    imageUrl: '/images/weapons/spear.png',
    label: 'Spear',
    type: 'melee',
  },
];

export const heavySpecializations: ContestantSpecialization[] = [
  {
    classType: 'heavy',
    description: 'Enables the user to run circles around opponents.',
    id: 'charge-n-slam',
    imageUrl: '/images/specializations/charge-n-slam.png',
    label: "Charge 'N' Slam",
  },
  {
    classType: 'heavy',
    description:
      'Shoots goo to impair enemies, making it highly frustrating for them.',
    id: 'goo-gun',
    imageUrl: '/images/specializations/goo-gun.png',
    label: 'Goo Gun',
  },
  {
    classType: 'heavy',
    description:
      'Deploys a shield, which is adjusted regularly based on patch updates.',
    id: 'mesh-shield',
    imageUrl: '/images/specializations/mesh-shield.png',
    label: 'Mesh Shield',
  },
  {
    classType: 'heavy',
    description: 'Inspired by Roadhog’s ability from the video game Overwatch.',
    id: 'winch-claw',
    imageUrl: '/images/specializations/winch-claw.png',
    label: 'Winch Claw',
  },
];
