import {
  type ContestantClass,
  type ContestantSpecialization,
  type ContestantWeapon,
} from '../schema';

export const heavyClass: ContestantClass = {
  description:
    'Durable powerhouse specializing in area control and high damage output.',
  healthPoints: 350,
  imageUrl: '/images/contestants/heavy.png',
  label: 'Heavy',
  regenerationSeconds: 10,
  type: 'heavy',
};

export const heavyWeapons: ContestantWeapon[] = [
  {
    classType: 'heavy',
    damageBodyMax: 44,
    damageBodyMin: 44,
    damageCriticalMultiplier: 2,
    damageCriticalType: 'headshot',
    description: 'Dual pistols also used as snipers',
    id: '50-akimbo',
    imageUrl: '/images/weapons/50-akimbo.png',
    label: '.50 Akimbo',
    type: 'handgun',
  },
  {
    classType: 'heavy',
    damageBodyMax: 30,
    damageBodyMin: 30,
    damageCriticalMultiplier: 1,
    damageCriticalType: 'none',
    description:
      'Flamethrower that is always more effective when used by your enemies',
    id: 'flamethrower',
    imageUrl: '/images/weapons/flamethrower.png',
    label: 'Flamethrower',
    type: 'assault-rifle',
  },
  {
    classType: 'heavy',
    damageBodyMax: 100,
    damageBodyMin: 100,
    damageCriticalMultiplier: 1,
    damageCriticalType: 'none',
    description:
      'A shotgun with slugs that can destroy walls/floors in four shots.',
    id: 'ks-23',
    imageUrl: '/images/weapons/ks-23.png',
    label: 'KS-23',
    type: 'shotgun',
  },
  {
    classType: 'heavy',
    damageBodyMax: 22,
    damageBodyMin: 22,
    damageCriticalMultiplier: 1.5,
    damageCriticalType: 'headshot',
    description: 'Like the M60 but with more accuracy and a smaller clip size',
    id: 'lewis-gun',
    imageUrl: '/images/weapons/lewis-gun.png',
    label: 'Lewis Gun',
    type: 'lmg',
  },
  {
    classType: 'heavy',
    damageBodyMax: 83,
    damageBodyMin: 83,
    damageCriticalMultiplier: 1,
    damageCriticalType: 'none',
    description: 'A grenade launcher that has boing-y grenades',
    id: 'm32gl',
    imageUrl: '/images/weapons/m32gl.png',
    label: 'M32GL',
    type: 'grenade-launcher',
  },
  {
    classType: 'heavy',
    damageBodyMax: 19,
    damageBodyMin: 19,
    damageCriticalMultiplier: 1.5,
    damageCriticalType: 'headshot',
    description: 'Like the Lewis Gun but less accurate and bigger clip size',
    id: 'm60',
    imageUrl: '/images/weapons/m60.png',
    label: 'M60',
    type: 'lmg',
  },
  {
    classType: 'heavy',
    damageBodyMax: 78,
    damageBodyMin: 13,
    damageCriticalMultiplier: 1,
    damageCriticalType: 'none',
    description:
      'One of those mysterious guns that is typically ass except for some people who have figured it out. You can be one of the ones to figure it out!',
    id: 'sa1216',
    imageUrl: '/images/weapons/sa1216.png',
    label: 'SA1216',
    type: 'shotgun',
  },
  {
    classType: 'heavy',
    damageBodyMax: 30,
    damageBodyMin: 30,
    damageCriticalMultiplier: 1.5,
    damageCriticalType: 'headshot',
    description: 'I like this gun. Thanks!',
    id: 'shak-50',
    imageUrl: '/images/weapons/shak-50.png',
    label: 'ShAk-50',
    type: 'shotgun',
  },
  {
    classType: 'heavy',
    damageBodyMax: 115,
    damageBodyMin: 115,
    damageCriticalMultiplier: 1.74,
    damageCriticalType: 'alt',
    description: 'Beeg hammer for beeg smash kaboom',
    id: 'sledgehammer',
    imageUrl: '/images/weapons/sledgehammer.png',
    label: 'Sledgehammer',
    type: 'melee',
  },
  {
    classType: 'heavy',
    damageBodyMax: 90,
    damageBodyMin: 65,
    damageCriticalMultiplier: 1.62,
    damageCriticalType: 'alt',
    description: 'Beeg spear for beeg swing and spin wahoo',
    id: 'spear',
    imageUrl: '/images/weapons/spear.png',
    label: 'Spear',
    type: 'melee',
  },
];

export const heavySpecializations: ContestantSpecialization[] = [
  {
    classType: 'heavy',
    description: 'Run around in a circle around your opponents',
    id: 'charge-n-slam',
    imageUrl: '/images/specializations/charge-n-slam.png',
    label: "Charge 'N' Slam",
  },
  {
    classType: 'heavy',
    description: 'Shoot goo and be super fucking annoying',
    id: 'goo-gun',
    imageUrl: '/images/specializations/goo-gun.png',
    label: 'Goo Gun',
  },
  {
    classType: 'heavy',
    description:
      'Hold a shield up - this gets nerfed or buffed depending on how Embark is feeling at patch time.',
    id: 'mesh-shield',
    imageUrl: '/images/specializations/mesh-shield.png',
    label: 'Mesh Shield',
  },
  {
    classType: 'heavy',
    description:
      "Roadhog's specialization from the formerly acclaimed video game Overwatch",
    id: 'winch-claw',
    imageUrl: '/images/specializations/winch-claw.png',
    label: 'Winch Claw',
  },
];
