import { type Patch } from '../types';

export const patch1100: Patch = {
  date: new Date('2026-07-09T11:00:00'),
  description:
    'Season 11 launched with a full melee rework (Stamina and Precision systems), a contextual quick-melee kick, and a wide balance pass across weapons, gadgets, and specializations.',
  originalUrl: 'https://www.reachthefinals.com/patchnotes/11-00',
  patchNotes: [
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      devNote:
        'Melee should be a viable style of play with a fair chance to win, without being frustrating to play against.',
      note: 'Melee rework: all melee weapons now use Stamina (controls lunges) and Precision (hits inside the precision zone deal critical damage, glancing hits deal less).',
      section: 'balance',
      target: 'general',
    },
    {
      adjustmentType: 'nerf',
      category: 'weapons',
      note: 'Quick melee damage decreased from 40 to 25. Added a contextual Kick at full Stamina that pushes targets back ~5m.',
      section: 'balance',
      target: 'general',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      devNote:
        'The 93R has been a strong outlier since its last buffs, so damage reverts while ammo goes up instead.',
      note: 'Decreased damage from 25 to 24 and increased ammo from 21 to 27.',
      section: 'balance',
      target: '93r',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Increased damage from 44 to 46.',
      section: 'balance',
      target: '50-akimbo',
    },
    {
      adjustmentType: 'nerf',
      category: 'weapons',
      note: 'Decreased fire rate from 540 to 530 RPM.',
      section: 'balance',
      target: 'fcar',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Increased damage from 100 to 110 and decreased damage falloff multiplier from 0.7 to 0.64.',
      section: 'balance',
      target: 'ks-23',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Decreased dispersion in all aim states by 10%, reduced dispersion scaling during fast camera movement, and increased environmental damage from 30 to 35.',
      section: 'balance',
      target: 'm134-minigun',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Increased pellet damage from 12 to 13.',
      section: 'balance',
      target: 'model-1887',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Increased headshot multiplier from 1.5 to 1.75.',
      section: 'balance',
      target: 'pike-556',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Added Stamina and Precision. Precise hits deal 60, glancing hits 42; lunge distance increased from 3m to 4.5m. Backstab multiplier increased from 4.26 to 4.5 and charge time reduced from 0.8s to 0.65s.',
      section: 'balance',
      target: 'dagger',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Added Stamina and Precision. Removed the cross-swipe primary; precise hits deal 57x2, glancing 39x2. Deflect movement speed decreased by 50%. New Cross Slash (primary while deflecting) deals 140 precise / 84 base.',
      section: 'balance',
      target: 'dual-blades',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Added Stamina and Precision. Precise hits deal 82, glancing 57; lunge distance increased from 3m to 4m. Shield block now gives full frontal protection at -25% movement speed. New Shield Bash deals 40 with ~5m knockback.',
      section: 'balance',
      target: 'riot-shield',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Added Stamina and Precision. Primary deals 120 precise / 90 base, secondary 200 precise / 150 base. Lunge distance increased from 4.5m to 5m.',
      section: 'balance',
      target: 'sledgehammer',
    },
    {
      adjustmentType: 'nerf',
      category: 'weapons',
      note: 'Added Stamina and Precision. Primary combo reduced to two attacks (74 precise / 55 base) and lunge distance decreased from 7.5m to 5m. Spin is now a stamina-gated 75/100/126 sequence.',
      section: 'balance',
      target: 'spear',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Added Stamina and Precision. Precise hits deal 110, glancing 71; lunge distance increased from 3m to 4.25m. Secondary lunge reaches ~10m with Stamina, ~5m without.',
      section: 'balance',
      target: 'sword',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Increased projectiles blocked from 5 to 6 and health from 160 to 175. Cooldown no longer regenerates while deployed (5s on pickup, 15s on remote retrieval, 30s on destruction).',
      section: 'balance',
      target: 'aps-turret',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Decreased arm time when deployed from 1.5s to 1s.',
      section: 'balance',
      target: 'breach-charge',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Can now reshape Gateways to immediately disable them.',
      section: 'balance',
      target: 'data-reshaper',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Increased health from 350 to 425.',
      section: 'balance',
      target: 'hover-pad',
    },
    {
      adjustmentType: 'nerf',
      category: 'specializations',
      devNote:
        'Stealth is meant for a slower hide-and-seek playstyle rather than high-speed use.',
      note: 'Decreased minimum cloak duration from ~13s to ~11s. Energy drain is now minimal below run speed and maximal at run speed or faster.',
      section: 'balance',
      target: 'cloaking-device',
    },
    {
      adjustmentType: 'nerf',
      category: 'specializations',
      note: 'Decreased charges from 3 to 2 and decreased cooldown from 7.5s to 6.5s.',
      section: 'balance',
      target: 'evasive-dash',
    },
    {
      adjustmentType: 'nerf',
      category: 'specializations',
      note: 'Decreased victim stun from 0.25s to 0.1s, lock-in-place from 0.15s to 0.1s, and post-grab action delay from 0.25s to 0.1s.',
      section: 'balance',
      target: 'winch-claw',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Fixed an exploit that allowed firing faster than intended.',
      section: 'content-and-bug-fixes',
      target: 'cl-40',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Collision now matches the visuals more closely, and the third-person stance and FOV shift when raising were reduced.',
      section: 'content-and-bug-fixes',
      target: 'riot-shield',
    },
    {
      adjustmentType: 'neutral',
      category: 'gadget',
      note: 'Projectile no longer persists when a dematerialized surface rematerializes.',
      section: 'content-and-bug-fixes',
      target: 'lockbolt-launcher',
    },
    {
      adjustmentType: 'neutral',
      category: 'specializations',
      note: 'Improved hit registration on fast-moving targets and under packet loss, and fixed shots not registering on pulled players.',
      section: 'content-and-bug-fixes',
      target: 'winch-claw',
    },
    {
      adjustmentType: 'neutral',
      category: 'specializations',
      note: 'Improved floor-breaking consistency and fixed it not interrupting melee swings.',
      section: 'content-and-bug-fixes',
      target: 'charge-n-slam',
    },
  ],
  title: 'SEASON 11 | GALAXY MASTERS',
  version: '11.0.0',
};
