import { type Patch } from '../types';

export const patch11100: Patch = {
  date: new Date('2026-09-17T11:00:00'),
  description:
    'Update 11.10.0 brought back Respec Order (3.0) for two weeks. These archetype and weapon changes applied to Cashout only and expired with Season 11.',
  originalUrl: 'https://www.reachthefinals.com/patchnotes/s11-respec-order-3',
  patchNotes: [
    {
      adjustmentType: 'buff',
      category: 'contestants',
      changes: [
        { from: 150, stat: 'health', to: 175 },
        { from: 7, label: 'Regen delay', stat: 'other', to: 8, unit: 's' },
      ],
      note: 'Light health increased from 150 to 175, regen delay increased from 7s to 8s, and movement speed reduced across the board.',
      section: 'balance',
      temporary: true,
      target: 'light-contestant',
    },
    {
      adjustmentType: 'neutral',
      category: 'contestants',
      changes: [{ from: 350, stat: 'health', to: 325 }],
      note: 'Heavy health decreased from 350 to 325, with faster sprint and run speeds.',
      section: 'balance',
      temporary: true,
      target: 'heavy-contestant',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      changes: [{ from: 140, stat: 'damage', to: 150 }],
      note: 'Increased damage from 140 to 150.',
      section: 'balance',
      temporary: true,
      target: 'frag-grenade',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      changes: [{ from: 120, stat: 'damage', to: 140 }],
      note: 'Increased damage from 120 to 140.',
      section: 'balance',
      temporary: true,
      target: 'explosive-mine',
    },
    {
      adjustmentType: 'nerf',
      category: 'gadget',
      changes: [{ from: 25, stat: 'cooldown', to: 30 }],
      note: 'Increased cooldown from 25s to 30s.',
      section: 'balance',
      temporary: true,
      target: 'vanishing-bomb',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      changes: [
        { from: 85, label: 'Secondary damage', stat: 'other', to: 90 },
        { from: 340, label: 'Backstab damage', stat: 'other', to: 315 },
      ],
      note: 'Secondary base damage increased from 85 to 90, backstab damage decreased from 340 to 315.',
      section: 'balance',
      temporary: true,
      target: 'dagger',
    },
    {
      adjustmentType: 'nerf',
      category: 'weapons',
      changes: [
        { from: 50, stat: 'falloff-min-range', to: 35 },
        { from: 55, stat: 'falloff-max-range', to: 45 },
      ],
      note: 'Damage falloff now starts at 35m (from 50m) and ends at 45m (from 55m).',
      section: 'balance',
      temporary: true,
      target: 'lh1',
    },
    {
      adjustmentType: 'nerf',
      category: 'weapons',
      changes: [
        { from: 71, stat: 'damage', to: 65 },
        { from: 110, label: 'Precise damage', stat: 'other', to: 100 },
      ],
      note: 'Base damage decreased from 71 to 65 and precise damage from 110 to 100.',
      section: 'balance',
      temporary: true,
      target: 'sword',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 84, stat: 'damage', to: 88 }],
      note: 'Increased damage from 84 to 88.',
      section: 'balance',
      temporary: true,
      target: 'cb-01-repeater',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 45, stat: 'damage', to: 47 }],
      note: 'Increased damage from 45 to 47.',
      section: 'balance',
      temporary: true,
      target: 'chimera-xb',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Primary damage increased to 40 base / 60 precise, Cross Slash to 100 base / 150 precise.',
      section: 'balance',
      temporary: true,
      target: 'dual-blades',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 14, stat: 'damage', to: 15 }],
      note: 'Increased damage from 14 to 15.',
      section: 'balance',
      temporary: true,
      target: 'p90',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 49, stat: 'damage', to: 56 }],
      note: 'Increased damage from 49 to 56.',
      section: 'balance',
      temporary: true,
      target: 'pike-556',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Primary damage increased to 63 base / 90 precise.',
      section: 'balance',
      temporary: true,
      target: 'riot-shield',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 90, stat: 'damage', to: 95 }],
      note: 'Increased damage from 90 to 95 and decreased reload time.',
      section: 'balance',
      temporary: true,
      target: 'bfr-titan',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 500, stat: 'fire-rate', to: 520 }],
      note: 'Increased fire rate from 500 to 520 RPM.',
      section: 'balance',
      temporary: true,
      target: 'lewis-gun',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 580, stat: 'fire-rate', to: 590 }],
      note: 'Increased fire rate from 580 to 590 RPM.',
      section: 'balance',
      temporary: true,
      target: 'm60',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 83, stat: 'damage', to: 97 }],
      note: 'Increased damage from 83 to 97.',
      section: 'balance',
      temporary: true,
      target: 'm32gl',
    },
  ],
  title: 'UPDATE 11.10.0 | RESPEC ORDER 3.0',
  version: '11.10.0',
};
