import { type Patch } from '../types';

export const patch1000: Patch = {
  date: new Date('2026-03-26T11:00:00'),
  description:
    'Season 10 launched with new medium equipment and a broad balance pass across gadgets, specializations, and weapons.',
  originalUrl: 'https://www.reachthefinals.com/patchnotes/10-00',
  patchNotes: [
    {
      adjustmentType: 'addition',
      category: 'specializations',
      note: 'Added Shockwave specialization to the Medium archetype.',
      section: 'additions',
      target: 'shockwave',
    },
    {
      adjustmentType: 'addition',
      category: 'gadget',
      note: 'Added Hover Pad gadget to the Medium archetype.',
      section: 'additions',
      target: 'hover-pad',
    },
    {
      adjustmentType: 'addition',
      category: 'weapons',
      note: 'Added Chimera XB semi-automatic crossbow to the Medium archetype.',
      section: 'additions',
      target: 'chimera-xb',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Can now reshape objects through Dome Shield and Mesh Shield.',
      section: 'balance',
      target: 'data-reshaper',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      changes: [{ from: 40, stat: 'cooldown', to: 30 }],
      note: 'Decreased cooldown from 40s to 30s.',
      section: 'balance',
      target: 'lockbolt-launcher',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      changes: [{ from: 25, stat: 'cooldown', to: 18 }],
      note: 'Decreased cooldown from 25s to 18s.',
      section: 'balance',
      target: 'stun-gun',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      changes: [{ from: 40, stat: 'cooldown', to: 34 }],
      note: 'Decreased cooldown from 40s to 34s.',
      section: 'balance',
      target: 'sonar-grenade',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      changes: [{ from: 35, stat: 'cooldown', to: 25 }],
      note: 'Decreased cooldown from 35s to 25s.',
      section: 'balance',
      target: 'thermal-bore',
    },
    {
      adjustmentType: 'buff',
      category: 'specializations',
      note: 'Increased minimum and maximum cloaked duration.',
      section: 'balance',
      target: 'cloaking-device',
    },
    {
      adjustmentType: 'neutral',
      category: 'specializations',
      changes: [{ from: 10, stat: 'cooldown', to: 20 }, { from: 2, stat: 'charges', to: 3 }],
      note: 'Increased cooldown from 10s to 20s and increased ammo count from 2 to 3.',
      section: 'balance',
      target: 'dematerializer',
    },
    {
      adjustmentType: 'nerf',
      category: 'specializations',
      changes: [{ from: 6.5, stat: 'cooldown', to: 7.5 }],
      note: 'Increased cooldown from 6.5s to 7.5s.',
      section: 'balance',
      target: 'evasive-dash',
    },
    {
      adjustmentType: 'buff',
      category: 'specializations',
      changes: [{ from: 8, stat: 'cooldown', to: 7 }],
      note: 'Decreased cooldown from 8s to 7s.',
      section: 'balance',
      target: 'grappling-hook',
    },
    {
      adjustmentType: 'neutral',
      category: 'specializations',
      note: 'Increased damage and tracking speed with offsetting fire-rate/vision tuning and faster setup.',
      section: 'balance',
      target: 'guardian-turret',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 32, stat: 'magazine-size', to: 34 }],
      note: 'Increased magazine size from 32 to 34.',
      section: 'balance',
      target: 'akm',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Increased max damage and redistributed inner/outer blast damage profile while increasing self-damage multiplier.',
      section: 'balance',
      target: 'cl-40',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 520, stat: 'fire-rate', to: 540 }],
      note: 'Increased fire rate from 520 to 540 RPM.',
      section: 'balance',
      target: 'fcar',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      changes: [{ from: 250, stat: 'magazine-size', to: 300 }],
      note: 'Increased magazine size from 250 to 300.',
      section: 'balance',
      target: 'm134-minigun',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Tightened pellet spread and increased environmental damage per pellet.',
      section: 'balance',
      target: 'm26-matter',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Adjusted inner/outer blast radius profile for improved close-range viability.',
      section: 'balance',
      target: 'm32gl',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Updated recoil pattern to be smoother and less erratic.',
      section: 'balance',
      target: 'pike-556',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Lowered total damage while improving spread consistency and long-range usability.',
      section: 'balance',
      target: 'sh1900',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Updated projectile drag, velocity, and gravity profile to improve reliability.',
      section: 'balance',
      target: 'sr-84',
    },
  ],
  title: 'SEASON 10 | FANTASY LEAGUE',
  version: '10.0.0',
};
