import { type Patch } from '../types';

export const patch900: Patch = {
  date: new Date('2025-12-10T11:00:00'),
  description:
    'Season 9 launched with broad balance updates across gadgets, specializations, and weapons.',
  originalUrl: 'https://www.reachthefinals.com/patchnotes/900',
  patchNotes: [
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Decreased cooldown from 30s to 20s.',
      section: 'balance',
      target: 'breach-charge',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Increased outer radius from 5m to 5.5m and max damage radius from 2.5m to 2.75m.',
      section: 'balance',
      target: 'frag-grenade',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Decreased cooldown from 30s to 24s.',
      section: 'balance',
      target: 'gas-grenade',
    },
    {
      adjustmentType: 'nerf',
      category: 'gadget',
      note: 'Decreased max range from 70m to 50m.',
      section: 'balance',
      target: 'gateway',
    },
    {
      adjustmentType: 'neutral',
      category: 'gadget',
      note: 'Decreased ammo from 2 to 1 and reduced cooldown from 20s to 12s.',
      section: 'balance',
      target: 'glitch-grenade',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Decreased cooldown from 30s to 24s.',
      section: 'balance',
      target: 'pyro-grenade',
    },
    {
      adjustmentType: 'nerf',
      category: 'gadget',
      note: 'Decreased explosive damage from 80 to 55.',
      section: 'balance',
      target: 'pyro-mine',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Decreased fuse time from 2.5s to 1.75s and cooldown from 45s to 35s.',
      section: 'balance',
      target: 'thermal-bore',
    },
    {
      adjustmentType: 'buff',
      category: 'gadget',
      note: 'Increased damage from 100 to 110.',
      section: 'balance',
      target: 'rpg-7',
    },
    {
      adjustmentType: 'buff',
      category: 'specializations',
      note: 'Increased max health from 750 to 850 and can now block Winch Claw.',
      section: 'balance',
      target: 'mesh-shield',
    },
    {
      adjustmentType: 'nerf',
      category: 'specializations',
      note: 'Reduced stun duration and added break/retraction logic for edge cases and wall interactions.',
      section: 'balance',
      target: 'winch-claw',
    },
    {
      adjustmentType: 'nerf',
      category: 'weapons',
      note: 'Decreased damage from 26 to 24 and tightened effective range profile.',
      section: 'balance',
      target: '93r',
    },
    {
      adjustmentType: 'nerf',
      category: 'weapons',
      note: 'Decreased environmental damage and reduced fire rate.',
      section: 'balance',
      target: 'bfr-titan',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Increased third-hit combo damage from 65 to 100.',
      section: 'balance',
      target: 'dual-blades',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Reduced ADS dispersion across stances by ~30%.',
      section: 'balance',
      target: 'ks-23',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Increased damage from 22 to 23.',
      section: 'balance',
      target: 'lewis-gun',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Reduced ADS dispersion while crouched/standing still.',
      section: 'balance',
      target: 'm134-minigun',
    },
    {
      adjustmentType: 'neutral',
      category: 'weapons',
      note: 'Reduced early recoil but increased sustained recoil after the 30th bullet.',
      section: 'balance',
      target: 'm60',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Shortened tactical reload intro from 2.2s to 1.5s.',
      section: 'balance',
      target: 'model-1887',
    },
    {
      adjustmentType: 'buff',
      category: 'weapons',
      note: 'Extended damage falloff ranges and increased max-range multiplier.',
      section: 'balance',
      target: 'v9s',
    },
  ],
  title: 'SEASON 9 | DRAGON RISING',
  version: '9.0.0',
};
